
CONTIKI_PROJECT = example-energest
all: $(CONTIKI_PROJECT)

MODULES += os/services/shell

MAKE_MAC = MAKE_MAC_TSCH

MAKE_NET = MAKE_NET_NULLNET

CONTIKI = ../../..
include $(CONTIKI)/Makefile.include
