CONTIKI_PROJECT = leaf
all: $(CONTIKI_PROJECT)

MODULES += os/services/shell
MODULES += os/net/mac/tsch/sixtop


MAKE_MAC = MAKE_MAC_TSCH

CONTIKI = ../../../../..
include $(CONTIKI)/Makefile.include
